language: ruby
rvm:
  - 2.2.2
  - 2.3
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_script:
  - bundle update

script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Whatever Name"
  - bundle exec rspec spec
